Base/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Control_Coordinacion import views as Vistas_Control_Coordinacion
from Control_Seguimiento_Contable import views as Vistas_Control_Seguimiento_Contable
from Control_Seguimiento_Obra import views as Vistas_Control_Seguimiento_Obra
from Control_VU import views as Vistas_Control_VU
from Evaluacion import views as Vistas_Evaluacion
from Usuarios import views as Vistas_Usuarios
from Contribuyentes import views as Vistas_Contribuyentes
from Solicitudes import views as Vistas_Solicitudes
from Mensajeria import views as Vistas_Mensajeria
from COMAP_Control import views as Vistas_COMAP_Control
from WS import views as Vistas_WS
from WF import views as Vistas_WF
from Base import views as Vistas_Base 


urlpatterns = [
	
	path('template_paises_departamentos_localidades/', Vistas_Base.Paises_Departamentos_Localidades_TemplateView.as_view(template_name='template_paises_departamentos_localidades.html'), name='Template_Paises_Departamentos_Localidades'),
	path('listado_paises/', Vistas_Base.ListadoPaises.as_view(template_name='paises.html'), name='Listado_Paises'),
	path('crear_paises/', Vistas_Base.CrearPais.as_view(template_name='crear_pais.html'), name='Crear_Pais'),
	path('actualizar_paises/', Vistas_Base.ActualizarPais.as_view(template_name='actualizar_pais.html'), name='Actualizar_Pais'),
	path('crear_paises_individual/', Vistas_Base.Paises_CreateView.as_view(template_name='crear_pais_individual.html'), name='Crear_Pais_Individual'),
	path('actualizar_paises_individual/<int:pk>', Vistas_Base.Paises_UpdateView.as_view(template_name='actualizar_pais_individual.html'), name='Actualizar_Pais_Individual'),	
	path('eliminar_paises_individual/<int:pk>', Vistas_Base.Paises_DeleteView.as_view(template_name='eliminar_pais_individual.html'), name='Eliminar_Pais_Individual'),
	path('detalles_paises_individual/<int:pk>', Vistas_Base.Paises_DetailView.as_view(template_name='detalle_pais_individual.html'), name='Detalle_Pais_Individual'),
	
	path('listado_departamentos/', Vistas_Base.ListadoDepartamentos.as_view(template_name='departamentos.html'), name='Listado_Departamentos'),
	path('crear_departamentos_individual/', Vistas_Base.Departamentos_CreateView.as_view(template_name='crear_departamento_individual.html'), name='Crear_Departamento_Individual'),
	path('actualizar_departamentos_individual/<int:pk>', Vistas_Base.Departamentos_UpdateView.as_view(template_name='actualizar_departamento_individual.html'), name='Actualizar_Departamento_Individual'),	
	path('eliminar_departamentos_individual/<int:pk>', Vistas_Base.Departamentos_DeleteView.as_view(template_name='eliminar_departamento_individual.html'), name='Eliminar_Departamento_Individual'),
	path('detalles_departamentos_individual/<int:pk>', Vistas_Base.Departamentos_DetailView.as_view(template_name='detalle_departamento_individual.html'), name='Detalle_Departamento_Individual'),
	
	path('listado_localidades/', Vistas_Base.ListadoLocalidades.as_view(template_name='localidades.html'), name='Listado_Localidades'),
	path('crear_localidades_individual/', Vistas_Base.Localidades_CreateView.as_view(template_name='crear_localidad_individual.html'), name='Crear_Localidad_Individual'),
	path('actualizar_localidades_individual/<int:pk>', Vistas_Base.Localidades_UpdateView.as_view(template_name='actualizar_localidad_individual.html'), name='Actualizar_Localidad_Individual'),	
	path('eliminar_localidades_individual/<int:pk>', Vistas_Base.Localidades_DeleteView.as_view(template_name='eliminar_localidad_individual.html'), name='Eliminar_Localidad_Individual'),
	path('detalles_localidades_individual/<int:pk>', Vistas_Base.Localidades_DetailView.as_view(template_name='detalle_localidad_individual.html'), name='Detalle_Localidad_Individual'),
	
	path('listado_tipodocumento/', Vistas_Base.ListadoTipoDocumento.as_view(template_name='listado_tipo_documento.html'), name='Listado_Tipo_Documento'),
	path('crear_tipodocumento/', Vistas_Base.TipoDocumento_CreateView.as_view(template_name='crear_tipo_documento.html'), name='Crear_Tipo_Documento'),
	path('actualizar_tipodocumento/<int:pk>', Vistas_Base.TipoDocumento_UpdateView.as_view(template_name='actualizar_tipo_documento.html'), name='Actualizar_Tipo_Documento'),	
	path('eliminar_tipodocumento/<int:pk>', Vistas_Base.TipoDocumento_DeleteView.as_view(template_name='eliminar_tipo_documento.html'), name='Eliminar_Tipo_Documento'),
	path('detalles_tipodocumento/<int:pk>', Vistas_Base.TipoDocumento_DetailView.as_view(template_name='detalle_tipo_documento.html'), name='Detalle_Tipo_Documento'),

	path('template_categorias_subcategorias/', Vistas_Base.Categoria_SubCategoria_Inversiones_TemplateView.as_view(template_name='template_categorias_subcategorias.html'), name='Listado_Categoria_SubCategoria_Inversiones'),
	path('listado_categorias/', Vistas_Base.ListadoCategoriaInversiones.as_view(template_name='listado_categoria_inversiones.html'), name='Listado_Categorias'),
	path('crear_categorias_individual/', Vistas_Base.Categoria_Inversiones_CreateView.as_view(template_name='crear_categoria_inversiones.html'), name='Crear_Categoria_Inversion_Individual'),
	path('actualizar_categorias_individual/<int:pk>', Vistas_Base.Categoria_Inversiones_UpdateView.as_view(template_name='actualizar_categoria_inversiones.html'), name='Actualizar_Categoria_Inversion_Individual'),	
	path('eliminar_categorias_individual/<int:pk>', Vistas_Base.Categoria_Inversiones_DeleteView.as_view(template_name='eliminar_categoria_inversiones.html'), name='Eliminar_Categoria_Inversion_Individual'),
	path('detalles_categorias_individual/<int:pk>', Vistas_Base.Categoria_Inversiones_DetailView.as_view(template_name='detalle_categoria_inversiones.html'), name='Detalle_Categoria_Inversion_Individual'),

	path('listado_subcategorias/', Vistas_Base.ListadoSubCategoriaInversiones.as_view(template_name='listado_subcategoria_inversiones.html'), name='Listado_SubCategorias'),
	path('crear_subcategorias_individual/', Vistas_Base.SubCategoria_Inversiones_CreateView.as_view(template_name='crear_subcategoria_inversiones.html'), name='Crear_SubCategoria_Inversion_Individual'),
	path('actualizar_subcategorias_individual/<int:pk>', Vistas_Base.SubCategoria_Inversiones_UpdateView.as_view(template_name='actualizar_subcategoria_inversiones.html'), name='Actualizar_SubCategoria_Inversion_Individual'),	
	path('eliminar_subcategorias_individual/<int:pk>', Vistas_Base.SubCategoria_Inversiones_DeleteView.as_view(template_name='eliminar_subcategoria_inversiones.html'), name='Eliminar_SubCategoria_Inversion_Individual'),
	path('detalles_subcategorias_individual/<int:pk>', Vistas_Base.SubCategoria_Inversiones_DetailView.as_view(template_name='detalle_subcategoria_inversiones.html'), name='Detalle_SubCategoria_Inversion_Individual'),
	
	path('listado_tipocontribuyente/', Vistas_Base.ListadoTipoContribuyente.as_view(template_name='listado_tipo_contribuyente.html'), name='Listado_Tipo_Contribuyente'),
	path('crear_tipocontribuyente/', Vistas_Base.Tipo_Contribuyente_CreateView.as_view(template_name='crear_tipo_contribuyente.html'), name='Crear_Tipo_Contribuyente'),
	path('actualizar_tipocontribuyente/<int:pk>', Vistas_Base.Tipo_Contribuyente_UpdateView.as_view(template_name='actualizar_tipo_contribuyente.html'), name='Actualizar_Tipo_Contribuyente'),	
	path('eliminar_tipocontribuyente/<int:pk>', Vistas_Base.Tipo_Contribuyente_DeleteView.as_view(template_name='eliminar_tipo_contribuyente.html'), name='Eliminar_Tipo_Contribuyente'),
	path('detalles_tipocontribuyente/<int:pk>', Vistas_Base.Tipo_Contribuyente_DetailView.as_view(template_name='detalle_tipo_contribuyente.html'), name='Detalle_Tipo_Contribuyente'),

	path('listado_ministerios/', Vistas_Base.ListadoMinisterios.as_view(template_name='listado_ministerios.html'), name='Listado_Ministerios'),
	path('crear_ministerio/', Vistas_Base.Ministerios_CreateView.as_view(template_name='crear_ministerio.html'), name='Crear_Ministerio'),
	path('actualizar_ministerio/<int:pk>', Vistas_Base.Ministerios_UpdateView.as_view(template_name='actualizar_ministerio.html'), name='Actualizar_Ministerio'),	
	path('eliminar_ministerio/<int:pk>', Vistas_Base.Ministerios_DeleteView.as_view(template_name='eliminar_ministerio.html'), name='Eliminar_Ministerio'),
	path('detalles_ministerio/<int:pk>', Vistas_Base.Ministerios_DetailView.as_view(template_name='detalle_ministerio.html'), name='Detalle_Ministerio'),

	path('template_tipogiro_girociiu/', Vistas_Base.TipoGiro_GiroCIIU_TemplateView.as_view(template_name='template_tipogiro_girociiu.html'), name='Listado_TipoGiro_GiroCIIU'),
	path('listado_tipogiro/', Vistas_Base.ListadoTipoGiro.as_view(template_name='listado_tipo_giro.html'), name='Listado_TipoGiro'),
	path('crear_tipogiro_individual/', Vistas_Base.TipoGiro_CreateView.as_view(template_name='crear_tipo_giro.html'), name='Crear_Tipo_Giro_Individual'),
	path('actualizar_tipogiro_individual/<int:pk>', Vistas_Base.TipoGiro_UpdateView.as_view(template_name='actualizar_tipo_giro.html'), name='Actualizar_Tipo_Giro_Individual'),	
	path('eliminar_tipogiro_individual/<int:pk>', Vistas_Base.TipoGiro_DeleteView.as_view(template_name='eliminar_tipo_giro.html'), name='Eliminar_Tipo_Giro_Individual'),
	path('detalles_tipogiro_individual/<int:pk>', Vistas_Base.TipoGiro_DetailView.as_view(template_name='detalle_tipo_giro.html'), name='Detalle_Tipo_Giro_Individual'),

	path('listado_girociiu/', Vistas_Base.ListadoGiroCIIU.as_view(template_name='listado_giro_ciiu.html'), name='Listado_Giro_CIIU'),
	path('crear_girociiu_individual/', Vistas_Base.Giro_CIIU_CreateView.as_view(template_name='crear_giro_ciiu.html'), name='Crear_Giro_CIIU_Individual'),

COMAP_Control/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Control_Coordinacion import views
from Control_Seguimiento_Contable import views
from Control_Seguimiento_Obra import views
from Control_VU import views
from Evaluacion import views
from Usuarios import views
from Contribuyentes import views
from Solicitudes import views
from Mensajeria import views
from COMAP_Control import views
from WS import views
from WF import views
from Base import views

urlpatterns = [
	path('', include(('Usuarios.urls','Usuarios'), namespace='Usuarios')),
	path('', include(('WS.urls','WS'), namespace='WS')),
	path('', include(('Solicitudes.urls','Solicitudes'), namespace='Solicitudes')),
	path('', include(('Base.urls','Base'), namespace='Base')),
	path('', include(('Contribuyentes.urls','Contribuyentes'), namespace='Contribuyentes')),
	path('admin/', admin.site.urls),

]

WF/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Control_Coordinacion import views as Vistas_Control_Coordinacion
from Control_Seguimiento_Contable import views as Vistas_Control_Seguimiento_Contable
from Control_Seguimiento_Obra import views as Vistas_Control_Seguimiento_Obra
from Control_VU import views as Vistas_Control_VU
from Evaluacion import views as Vistas_Evaluacion
from Usuarios import views as Vistas_Usuarios
from Contribuyentes import views as Vistas_Contribuyentes
from Solicitudes import views as Vistas_Solicitudes
from Mensajeria import views as Vistas_Mensajeria
from COMAP_Control import views as Vistas_COMAP_Control
from WS import views as Vistas_WS
from WF import views as Vistas_WF 


urlpatterns = [
	
    #path('cotizaciones/', Vistas_WS.CotizacionesCreateView.as_view(template_name='cotizaciones.html'), name='Cotizaciones'),



]

Base/templates/respaldos/actualizar_pais_individual_14012020.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block head %}
        
{% endblock head %}


      {% block page_content_1 %}{% endblock page_content_1 %}
      {% block page_content_2 %}{% endblock page_content_2 %}
      {% block page_content_3 %}{% endblock page_content_3 %}
      {% block page_content_4 %}
        {% block jumbotron %}
          {% block jumbotron_title %}
              
          {% endblock jumbotron_title %}
          {% block jumbotron_content %}
          <!-- <div class="container mb-10" id="acordion_cargar_cotizaciones" style="width: 100%; margin:">  tabindex="-1" 
            <div class="row mb-10"> -->
              <div class="accordion" id="accordionSolicitudes">
                  <div class="card border-left-primary shadow">
                    <div class="card-header" id="headingOne">
                      <h2 class="">
                        <button class="btn btn-primary collapsed" type="button" data-toggle="collapse" data-target="#collapseSolicitudes" aria-expanded="true" aria-controls="collapseOne">
                          Paises
                        </button>
                      </h2>
                    </div>

                     <div id="collapseSolicitudes" class="collapse" aria-labelledby="headingOne" data-parent="#accordionSolicitudes">
                      <div class="card-body">
                        
                        <form role="form" action="{% url 'Base:Actualizar_Pais_Individual' paises.pk %}" method="post">
                          <h3>Actualizar Pais</h3>
                          {% csrf_token %}
                          <div class="panel panel-default">
                                  <div class="panel-body">
                                          {{ form.as_p }}
                                          
                                  </div>
                          </div>
                          <div class="col-lg-12 text-right">
                                  <input type="submit" class="btn btn-primary" name="submit" value="Guardar">
                                  <a type="button" class="btn btn-default" href="{% url 'Base:Listado_Paises' %}">
                                          Cancelar
                                  </a>
                          </div>
                          </form>

                        



                      </div>
                    </div>
                  </div>
              </div>    
            <!--</div>  
          </div>  -->
         
                       
          {% endblock jumbotron_content %}
        {% endblock jumbotron %}
      {% endblock page_content_4 %}

      {% block jscript %}
      <script src='{% static "js/jquery.formset.js" %}'></script>
      </script>
      <script type="text/javascript">
          $('.formset_row-{{ departamento_form_set.prefix }}').formset({
              addText: 'Agregar Nuevo Formulario',
              deleteText: 'Remover Formulario',
              prefix: '{{ departamento_form_set.prefix }}',
              addCssClass: 'add-row',
              deleteCssClass: 'delete-row',
          });
      </script>
      <script>
      $(document).ready(function()
      {
          var table = $('#tabla').dataTable( {
              "language": {
                      url: "/static/localizacion/es_ES.json"
              }
          } );
      });
      </script>
      {% endblock jscript %}

Base/templates/respaldos/crear_pais_06012020.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block head %}
        
{% endblock head %}


      {% block page_content_1 %}{% endblock page_content_1 %}
      {% block page_content_2 %}{% endblock page_content_2 %}
      {% block page_content_3 %}{% endblock page_content_3 %}
      {% block page_content_4 %}
        {% block jumbotron %}
          {% block jumbotron_title %}
              
          {% endblock jumbotron_title %}
          {% block jumbotron_content %}
          <!-- <div class="container mb-10" id="acordion_cargar_cotizaciones" style="width: 100%; margin:">  tabindex="-1" 
            <div class="row mb-10"> -->
              <div class="accordion" id="accordionSolicitudes">
                  <div class="card border-left-primary shadow">
                    <div class="card-header" id="headingOne">
                      <h2 class="">
                        <button class="btn btn-primary collapsed" type="button" data-toggle="collapse" data-target="#collapseSolicitudes" aria-expanded="true" aria-controls="collapseOne">
                          Paises
                        </button>
                      </h2>
                    </div>

                     <div id="collapseSolicitudes" class="collapse" aria-labelledby="headingOne" data-parent="#accordionSolicitudes">
                      <div class="card-body">
                        
                        <form role="form" action="{% url 'Base:Crear_Pais' %}" method="post">
                          <h3>Crear Pais / Departamento </h3>
                          {% csrf_token %}
                          <div class="panel panel-default">
                                  <div class="panel-body">
                                          {{ form.as_p }}
                                          {{ departamento_form_set.management_form }}
                                          <table>
                                          {% for departamento_form in departamento_form_set %}
                                                  <tr class="row">
                                                  <div class="row {% cycle 'row1' 'row2' %} formset_row-{{ departamento_form_set.prefix }}">
                                                          <div class="col-lg-4">
                                                                  <label>Descripcion</label>
                                                                  {% if departamento_form.descripcion.errors %}
                                                                          {% for error in departamento_form.descripcion.errors %}
                                                                          <div class="alert alert-danger alert-dismissible" role="alert">
                                                                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                                                          <span aria-hidden="true">&times;</span>
                                                                                  </button>
                                                                                  <strong>Error: </strong> {{ error|escape }}
                                                                          </div>
                                                                          {% endfor %}
                                                                  {% endif %}
                                                                  {{ departamento_form.descripcion }}
                                                          </div>
                                                          <div class="col-lg-4">
                                                                  <label>UC</label>
                                                                  {% if departamento_form.uc.errors %}
                                                                          {% for error in departamento_form.uc.errors %}
                                                                          <div class="alert alert-danger alert-dismissible" role="alert">
                                                                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                                                          <span aria-hidden="true">&times;</span>
                                                                                  </button>
                                                                                  <strong>Error: </strong> {{ error|escape }}
                                                                          </div>
                                                                          {% endfor %}
                                                                  {% endif %}
                                                                  {{ departamento_form.uc }}
                                                          </div>
                                                          <a type="button" class="btn btn-sm btn-default deleteCssClass data-formset-delete-button delete-row" href="javascript:void(0)">
                                                          {% trans 'delete' %} Eliminar
                                                          </a>                                                          
                                                  </div>
                                                  </tr>
                                          {% endfor %}
                                          </table>
                                  </div>
                          </div>
                          <div class="col-lg-12 text-right">
                                  <input type="submit" class="btn btn-primary" name="submit" value="Guardar">
                                  <a type="button" class="btn btn-default" href="{% url 'Base:Listado_Paises' %}">
                                          Cancelar
                                  </a>
                          </div>
                          </form>

                        



                      </div>
                    </div>
                  </div>
              </div>    
            <!--</div>  
          </div>  -->
         
                       
          {% endblock jumbotron_content %}
        {% endblock jumbotron %}
      {% endblock page_content_4 %}

      {% block jscript %}
      <script src='{% static "js/jquery.formset.js" %}'></script>
      </script>
      <script type="text/javascript">
          $('.formset_row-{{ departamento_form_set.prefix }}').formset({
              addText: 'Agregar Nuevo Formulario',
              deleteText: 'Remover Formulario',
              prefix: '{{ departamento_form_set.prefix }}',
              addCssClass: 'add-row',
              deleteCssClass: 'delete-row',
          });
      </script>
      <script>
      $(document).ready(function()
      {
          var table = $('#tabla').dataTable( {
              "language": {
                      url: "/static/localizacion/es_ES.json"
              }
          } );
      });
      </script>
      {% endblock jscript %}

Base/templates/respaldos/crear_pais_individual_14012020.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block head %}
        
{% endblock head %}


      {% block page_content_1 %}{% endblock page_content_1 %}
      {% block page_content_2 %}{% endblock page_content_2 %}
      {% block page_content_3 %}{% endblock page_content_3 %}
      {% block page_content_4 %}
        {% block jumbotron %}
          {% block jumbotron_title %}
              
          {% endblock jumbotron_title %}
          {% block jumbotron_content %}
          <!-- <div class="container mb-10" id="acordion_cargar_cotizaciones" style="width: 100%; margin:">  tabindex="-1" 
            <div class="row mb-10"> -->
              <div class="accordion" id="accordionSolicitudes">
                  <div class="card border-left-primary shadow">
                    <div class="card-header" id="headingOne">
                      <h2 class="">
                        <button class="btn btn-primary collapsed" type="button" data-toggle="collapse" data-target="#collapseSolicitudes" aria-expanded="true" aria-controls="collapseOne">
                          Paises
                        </button>
                      </h2>
                    </div>

                     <div id="collapseSolicitudes" class="collapse" aria-labelledby="headingOne" data-parent="#accordionSolicitudes">
                      <div class="card-body">
                        
                        <form role="form" action="{% url 'Base:Crear_Pais_Individual' %}" method="post">
                          <h3>Crear Pais</h3>
                          {% csrf_token %}
                          <div class="panel panel-default">
                                  <div class="panel-body">
                                          {{ form.as_p }}
                                          
                                  </div>
                          </div>
                          <div class="col-lg-12 text-right">
                                  <input type="submit" class="btn btn-primary" name="submit" value="Guardar">
                                  <a type="button" class="btn btn-default" href="{% url 'Base:Listado_Paises' %}">
                                          Cancelar
                                  </a>
                          </div>
                          </form>

                        



                      </div>
                    </div>
                  </div>
              </div>    
            <!--</div>  
          </div>  -->
         
                       
          {% endblock jumbotron_content %}
        {% endblock jumbotron %}
      {% endblock page_content_4 %}

      {% block jscript %}
      <script src='{% static "js/jquery.formset.js" %}'></script>
      </script>
      <script type="text/javascript">
          $('.formset_row-{{ departamento_form_set.prefix }}').formset({
              addText: 'Agregar Nuevo Formulario',
              deleteText: 'Remover Formulario',
              prefix: '{{ departamento_form_set.prefix }}',
              addCssClass: 'add-row',
              deleteCssClass: 'delete-row',
          });
      </script>
      <script>
      $(document).ready(function()
      {
          var table = $('#tabla').dataTable( {
              "language": {
                      url: "/static/localizacion/es_ES.json"
              }
          } );
      });
      </script>
      {% endblock jscript %}

Base/templates/respaldos/eliminar_pais_individual_07012020.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block head %}
        
{% endblock head %}


      {% block page_content_1 %}{% endblock page_content_1 %}
      {% block page_content_2 %}{% endblock page_content_2 %}
      {% block page_content_3 %}{% endblock page_content_3 %}
      {% block page_content_4 %}
        {% block jumbotron %}
          {% block jumbotron_title %}
              
          {% endblock jumbotron_title %}
          {% block jumbotron_content %}
          <!-- <div class="container mb-10" id="acordion_cargar_cotizaciones" style="width: 100%; margin:">  tabindex="-1" 
            <div class="row mb-10"> -->
              <div class="accordion" id="accordionSolicitudes">
                  <div class="card border-left-primary shadow">
                    <div class="card-header" id="headingOne">
                      <h2 class="">
                        <button class="btn btn-primary collapsed" type="button" data-toggle="collapse" data-target="#collapseSolicitudes" aria-expanded="true" aria-controls="collapseOne">
                          Paises
                        </button>
                      </h2>
                    </div>

                     <div id="collapseSolicitudes" class="collapse" aria-labelledby="headingOne" data-parent="#accordionSolicitudes">
                      <div class="card-body">
                        
                        <form role="form" action="{% url 'Base:Eliminar_Pais_Individual' paises.pk %}" method="post">
                          <h3>Eliminar Pais</h3>
                          {% csrf_token %}
                          <div class="panel panel-default">
                                  <div class="panel-body">
                                          ¿Eliminar {{ paises.descripcion }} ?
                                          
                                  </div>
                          </div>
                          <div class="col-lg-12 text-right">
                                  <input type="submit" class="btn btn-danger" name="submit" value="Eliminar">
                                  <a type="button" class="btn btn-default" href="{% url 'Base:Listado_Paises' %}">
                                          Cancelar
                                  </a>
                          </div>
                          </form>

                        



                      </div>
                    </div>
                  </div>
              </div>    
            <!--</div>  
          </div>  -->
         
                       
          {% endblock jumbotron_content %}
        {% endblock jumbotron %}
      {% endblock page_content_4 %}

      {% block jscript %}
      <script src='{% static "js/jquery.formset.js" %}'></script>
      </script>
      <script type="text/javascript">
          $('.formset_row-{{ departamento_form_set.prefix }}').formset({
              addText: 'Agregar Nuevo Formulario',
              deleteText: 'Remover Formulario',
              prefix: '{{ departamento_form_set.prefix }}',
              addCssClass: 'add-row',
              deleteCssClass: 'delete-row',
          });
      </script>
      <script>
      $(document).ready(function()
      {
          var table = $('#tabla').dataTable( {
              "language": {
                      url: "/static/localizacion/es_ES.json"
              }
          } );
      });
      </script>
      {% endblock jscript %}