COMAP_Control/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Control_Coordinacion import views
from Control_Seguimiento_Contable import views
from Control_Seguimiento_Obra import views
from Control_VU import views
from Evaluacion import views
from Usuarios import views
from Contribuyentes import views
from Solicitudes import views
from Mensajeria import views
from COMAP_Control import views
from WS import views
from WF import views
from Base import views

urlpatterns = [
	path('', include(('Usuarios.urls','Usuarios'), namespace='Usuarios')),
	path('', include(('WS.urls','WS'), namespace='WS')),
	path('', include(('Solicitudes.urls','Solicitudes'), namespace='Solicitudes')),
	path('', include(('Base.urls','Base'), namespace='Base')),
	path('', include(('Contribuyentes.urls','Contribuyentes'), namespace='Contribuyentes')),
	path('admin/', admin.site.urls),

]

Usuarios/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Control_Coordinacion import views as Vistas_Control_Coordinacion
from Control_Seguimiento_Contable import views as Vistas_Control_Seguimiento_Contable
from Control_Seguimiento_Obra import views as Vistas_Control_Seguimiento_Obra
from Control_VU import views as Vistas_Control_VU
from Evaluacion import views as Vistas_Evaluacion
from Usuarios import views as Vistas_Usuarios
from Contribuyentes import views as Vistas_Contribuyentes
from Solicitudes import views as Vistas_Solicitudes
from Mensajeria import views as Vistas_Mensajeria
from COMAP_Control import views as Vistas_COMAP_Control
from WS import views as Vistas_WS
from WF import views as Vistas_WF 


urlpatterns = [
	
    path('', Vistas_COMAP_Control.Home.as_view(), name='MiInicio'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='Login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='login.html'), name='Logout'),
    path('registro_contribuyente/', Vistas_Usuarios.MultiContribuyenteCreateView.as_view(template_name='registrocontribuyente.html'), name='Registro_Contribuyente'),
    path('contribuyente_grabado/', Vistas_Usuarios.ContribuyenteSuccessView.as_view(template_name='contribuyentegrabado.html'), name='Contribuyente_Grabado'),
    path('registro_personafisica/', Vistas_Usuarios.MultiPersonaFisicaCreateView.as_view(template_name='registropersonafisica.html'), name='Registro_PersonaFisica'),
    path('personafisica_grabado/', Vistas_Usuarios.PersonaFisicaSuccessView.as_view(template_name='personafisicagrabado.html'), name='PersonaFisica_Grabado'),
    #path('activate/<slug:uidb64>/<slug:token>/', Vistas_Usuarios.Activate.as_view(), name='activate'),
    #path('activate/(?P<uidb64>[-a-zA-Z0-9_]+)/(?P<token>[-a-zA-Z0-9_]+)/$', Vistas_Usuarios.Activate.as_view(), name='activate'),
    path('activate/<slug:uidb64>/<slug:token>/<slug:key>/', Vistas_Usuarios.Activate.as_view(), name='activate'),
    re_path('activate/(?P<uidb64>[-a-zA-Z0-9_]+)/(?P<token>[-a-zA-Z0-9_]+)/(?P<key>[-a-zA-Z0-9_]+)/$', Vistas_Usuarios.Activate.as_view(), name='activate2'),
    #path('cotizaciones/', Vistas_WS.CotizacionesCreateView.as_view(template_name='cotizaciones.html'), name='Cotizaciones'),



]

WF/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Control_Coordinacion import views as Vistas_Control_Coordinacion
from Control_Seguimiento_Contable import views as Vistas_Control_Seguimiento_Contable
from Control_Seguimiento_Obra import views as Vistas_Control_Seguimiento_Obra
from Control_VU import views as Vistas_Control_VU
from Evaluacion import views as Vistas_Evaluacion
from Usuarios import views as Vistas_Usuarios
from Contribuyentes import views as Vistas_Contribuyentes
from Solicitudes import views as Vistas_Solicitudes
from Mensajeria import views as Vistas_Mensajeria
from COMAP_Control import views as Vistas_COMAP_Control
from WS import views as Vistas_WS
from WF import views as Vistas_WF 


urlpatterns = [
	
    #path('cotizaciones/', Vistas_WS.CotizacionesCreateView.as_view(template_name='cotizaciones.html'), name='Cotizaciones'),



]

templates/activation.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}{% endblock head %}


      {% block page_content_1 %}{% endblock page_content_1 %}
      {% block page_content_2 %}{% endblock page_content_2 %}
      {% block page_content_3 %}{% endblock page_content_3 %}
      {% block page_content_4 %}
        {% block jumbotron %}
          {% block jumbotron_title %}
              
          {% endblock jumbotron_title %}
          {% block jumbotron_content %}
          <div class="container" id="content" tabindex="-1" style="background-color: #005A9B; color: #fff;">
            <div class="row justify-content-center">
            <img id="logo_DATABITICS_COMAP" src='{% static "img/sepi.jpg" %}' alt="Sistema de Exoneraciones de Proyectos de Inversión." style="height:100px; width:100px;" />
                <form method="POST" action="" name="Form_Html_Activacion" style="width:80%;margin:0 auto" id="Form_Html_Activacion" target="_self">
                  <p><label id="" class=""><h1>Cuenta Activada</h1></label></p>
                  <p><label id="" class=""><h3>Debe Actualizar Contraseña</h3></label></p>
                  <p><label id="" class=""><h6>{{ Mensaje_Error }}</h6></label></p>
                    {% csrf_token %}
                    <!-- {{ form }} --> 
                    <!--
                    <div class="form-group"><label id="labelOldPassword">Contraseña Antigua</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_old_password" type="password" size="25" name="old_password" class="form-control" autofocus required />
                        </div>
                    </div>
                    -->
                    <div class="form-group"><label id="labelNewPassword1">Contraseña Nueva</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_new_password1" type="password" size="25" name="new_password1" class="form-control" required />
                        </div>
                        <span class="helptext">
                          <ul>
                            <li>Su contraseña no puede asemejarse tanto a su otra información personal.</li>
                            <li>Su contraseña debe contener al menos 8 caracteres.</li>
                            <li>Su contraseña no puede ser una clave utilizada comunmente.</li>
                            <li>Su contraseña no puede ser completamente numérica.</li>
                          </ul>
                        </span>
                    </div>
                    <div class="form-group"><label id="labelNewPassword2">Confirmar Contraseña</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_new_password2" type="password" size="25" name="new_password2" class="form-control" required/>
                        </div>
                    </div>
                    <div class="form-group form-inline justify-content-between">
                      <div>
                          <input id="Activar Cuenta" type="submit" value="Establecer Contraseña" class="btn btn-primary" update="" form="Form_Html_Activacion" formmethod="POST" formaction='{% url "Usuarios:activate" uidb64 token key %}'/>
                      </div>
                      <div class="form-group form-inline justify-content-end">  
                        <div>
                            <a id="Redirigir a Inicio" href='{% url "Usuarios:MiInicio" %}' title="Redirigirme al Inicio" class="pull-right btn btn-sm btn-secondary">Redirigirme al Inicio</a>
                        </div>
                    </div>
                    </div>  
                </form>
            </div>    
          </div>
          {% endblock jumbotron_content %}
        {% endblock jumbotron %}
      {% endblock page_content_4 %}

templates/contribuyentegrabado.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}{% endblock head %}


      {% block page_content_1 %}{% endblock page_content_1 %}
      {% block page_content_2 %}{% endblock page_content_2 %}
      {% block page_content_3 %}{% endblock page_content_3 %}
      {% block page_content_4 %}
        {% block jumbotron %}
          {% block jumbotron_title %}
              
          {% endblock jumbotron_title %}
          {% block jumbotron_content %}
          <div class="container" id="content" tabindex="-1" style="background-color: #005A9B; color: #fff;">
            <div class="row justify-content-center">
            <img id="logo_DATABITICS_COMAP" src='{% static "img/sepi.jpg" %}' alt="Sistema de Exoneraciones de Proyectos de Inversión." style="height:100px; width:100px;" />
                  <label id="" class=""><h1>Contribuyente Guardado</h1></label>
            </div>    
          </div>
          {% endblock jumbotron_content %}
        {% endblock jumbotron %}
      {% endblock page_content_4 %}

templates/estructura_muestra_block.html
{% extends 'index.html' %}

{% block head %}{% endblock head %}

{% block body %}  

  {% block navbar %}
    {% block navbar_left %}{% endblock navbar_left %}
    {% block navbar_center %}{% endblock navbar_center %}
    {% block navbar_right %}{% endblock navbar_right %}
  {% endblock navbar %}

  {% block page_wrapper %}

    {% block side_bar %}
      {% block side_bar_content %}
        {% block side_bar_brand %}{% endblock side_bar_brand %}
        {% block side_bar_header %}
          {% block side_bar_header_imageuser %}{% endblock side_bar_header_imageuser %}
          {% block side_bar_header_infouser %}{% endblock side_bar_header_infouser %}
        {% endblock side_bar_header %}
        {% block side_bar_search %}{% endblock side_bar_search %}
        {% block side_bar_menu %}
          {% block side_bar_menu_header_1 %}{% endblock side_bar_menu_header_1 %}
            {% block side_bar_menu_itemdrop_1 %}{% endblock side_bar_menu_itemdrop_1 %}
          {% block side_bar_menu_header_2 %}{% endblock side_bar_menu_header_2 %}
            {% block side_bar_menu_itemdrop_2 %}{% endblock side_bar_menu_itemdrop_2 %}
        {% endblock side_bar_menu %}
      {% endblock side_bar_content %}
      {% block side_bar_footer %}{% endblock side_bar_footer %}
    {% endblock side_bar %}

    {% block page_content %}
      {% block page_content_1 %}{% endblock page_content_1 %}
      {% block page_content_2 %}{% endblock page_content_2 %}
      {% block page_content_3 %}{% endblock page_content_3 %}
      {% block page_content_4 %}
        {% block jumbotron %}
          {% block jumbotron_title %}{% endblock jumbotron_title %}
          {% block jumbotron_content %}{% endblock jumbotron_content %}
        {% endblock jumbotron %}
      {% endblock page_content_4 %}

    {% block footer_general %}
    {% endblock footer_general %}

    {% endblock page_content %}

  {% endblock page_wrapper %}
  {% block jscript %}{% endblock jscript %}       
{% endblock body %}

templates/login.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}{% endblock head %}


      {% block page_content_1 %}{% endblock page_content_1 %}
      {% block page_content_2 %}{% endblock page_content_2 %}
      {% block page_content_3 %}{% endblock page_content_3 %}
      {% block page_content_4 %}
        {% block jumbotron %}
          {% block jumbotron_title %}
              
          {% endblock jumbotron_title %}
          {% block jumbotron_content %}
          <div class="container" id="content" tabindex="-1" style="background-color: #005A9B; color: #fff;">
            <div class="row justify-content-center">
            <img id="logo_DATABITICS_COMAP" src='{% static "img/sepi.jpg" %}' alt="Sistema de Exoneraciones de Proyectos de Inversión." style="height:100px; width:100px;" />
                <form method="POST" action="" name="Form_Html_IniciarSesion" style="width:80%;margin:0 auto" id="Form_Html_IniciarSesion" target="_self">
                  <label id="" class=""><h1>Iniciar Sesión</h1></label>
                    {% csrf_token %}

                    <div class="form-group"><label id="labelUser">Usuario</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                            <input id="id_username" type="text" name="username" size="25" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group"><label id="labelPassword">Contraseña</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_password" type="password" size="25" name="password" class="form-control" />
                        </div>
                    </div>
                <!-- </form> -->  
                      <div class="form-group form-inline justify-content-between">
                              <div>
                                  <input id="iniciarSesion" type="submit" value="Iniciar sesión" class="btn btn-primary" update="form messages" form="Form_Html_IniciarSesion"/>
                              </div>
                            <div class="form-group form-inline justify-content-end">  
                              <div>
                                  <a id="linkCambiarPass" href="#" title="Olvidé mi contraseña" class="pull-right btn btn-sm btn-secondary">Olvidé mi contraseña</a>
                              </div>
                            </div>
                      </div>      
                            <div class="form-group form-inline justify-content-end">
                              <div>
                                  <a id="linkRegistrarme" href='{% url "Usuarios:Registro_Contribuyente" %}' title="Registrarme como contribuyente" class="pull-right btn btn-sm btn-secondary">Registrarme como Contribuyente</a>
                              </div>
                            </div>
                            <div class="form-group form-inline justify-content-end">
                              <div>
                                  <a id="linkRegistrarme" href='{% url "Usuarios:Registro_PersonaFisica" %}' title="Registrarme como Persona Fisica" class="pull-right btn btn-sm btn-secondary">Registrarme como Consultor</a>
                              </div>
                            </div>  
                </form>
            </div>    
          </div>
          {% endblock jumbotron_content %}
        {% endblock jumbotron %}
      {% endblock page_content_4 %}

templates/mail_activacion.html
{% autoescape off %}
Hi {{ user.username }},
Por favor, presiona el siguiente link para registrar la cuenta,

{{ domain }}{% url 'Usuarios:activate2' uidb64=uid token=token key=activation_key %}
Activation_Key: {{ activation_key }}
Fecha de Expiracion: {{ key_expires }}
{% endautoescape %}

templates/nuevolinkactivacion.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}{% endblock head %}


      {% block page_content_1 %}{% endblock page_content_1 %}
      {% block page_content_2 %}{% endblock page_content_2 %}
      {% block page_content_3 %}{% endblock page_content_3 %}
      {% block page_content_4 %}
        {% block jumbotron %}
          {% block jumbotron_title %}
              
          {% endblock jumbotron_title %}
          {% block jumbotron_content %}
          <div class="container" id="content" tabindex="-1" style="background-color: #005A9B; color: #fff;">
            <div class="row justify-content-center">
            <img id="logo_DATABITICS_COMAP" src='{% static "img/sepi.jpg" %}' alt="Sistema de Exoneraciones de Proyectos de Inversión." style="height:100px; width:100px;" />
                <form method="POST" action="" name="Form_Html_Nuevo_Link_Activacion" style="width:80%;margin:0 auto" id="Form_Html_Nuevo_Link_Activacion" target="_self">
                  <label id="" class=""><h1>Solicitar Nuevo Link de Activacion de Cuenta</h1></label>
                  <label id="" class=""><h3>Le enviaremos un correo con un nuevo link de activacion en caso de que la cuenta exista y no se encuentre activada al mail declarado en el registro de solicitud</h3></label>
                  <label id="" class=""><h6>{{ Mensaje_Error }}</h6></label>
                    {% csrf_token %}
                    <!-- {{ form }} -->
                    {{ form }}
                    
                    <div class="form-group form-inline justify-content-between">
                      <div>
                          <input id="Activar Cuenta" type="submit" value="Solicitar Nuevo Link de Activacion de Cuenta" class="btn btn-primary" update="" form="Form_Html_Nuevo_Link_Activacion" formmethod="POST" formaction='{% url "Usuarios:nuevo_link_activacion" user_id %}'/>
                      </div>
                    </div>  
                </form>
            </div>    
          </div>
          {% endblock jumbotron_content %}
        {% endblock jumbotron %}
      {% endblock page_content_4 %}

templates/personafisicagrabado.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}{% endblock head %}


      {% block page_content_1 %}{% endblock page_content_1 %}
      {% block page_content_2 %}{% endblock page_content_2 %}
      {% block page_content_3 %}{% endblock page_content_3 %}
      {% block page_content_4 %}
        {% block jumbotron %}
          {% block jumbotron_title %}
              
          {% endblock jumbotron_title %}
          {% block jumbotron_content %}
          <div class="container" id="content" tabindex="-1" style="background-color: #005A9B; color: #fff;">
            <div class="row justify-content-center">
            <img id="logo_DATABITICS_COMAP" src='{% static "img/sepi.jpg" %}' alt="Sistema de Exoneraciones de Proyectos de Inversión." style="height:100px; width:100px;" />
                  <label id="" class=""><h1>Persona Física Guardado</h1></label>
            </div>    
          </div>
          {% endblock jumbotron_content %}
        {% endblock jumbotron %}
      {% endblock page_content_4 %}

templates/registrocontribuyente.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}{% endblock head %}


      {% block page_content_1 %}{% endblock page_content_1 %}
      {% block page_content_2 %}{% endblock page_content_2 %}
      {% block page_content_3 %}{% endblock page_content_3 %}
      {% block page_content_4 %}
        {% block jumbotron %}
          {% block jumbotron_title %}
              
          {% endblock jumbotron_title %}
          {% block jumbotron_content %}
          <div class="container" id="content" tabindex="-1" style="background-color: #005A9B; color: #fff;">
            <div class="row justify-content-center">
            <img id="logo_DATABITICS_COMAP" src='{% static "img/sepi.jpg" %}' alt="Sistema de Exoneraciones de Proyectos de Inversión." style="height:100px; width:100px;"/>
                <form method="POST" action='{% url "Usuarios:Registro_Contribuyente" %}' name="Form_Html_RegistroContribuyente" enctype=multipart/form-data style="width:80%;margin:0 auto" id="Form_Html_RegistroContribuyente">
                  <label id="" class=""><h1>Registrar Contribuyente</h1></label>
                    {% csrf_token %}
                    <!--  {{ form.as_p }}   -->  
                    {{ form.non_field_errors }}
                    <div class="form-group"><label id="labelIdentificador" for="id_UsuarioMain-identificador">Identificador</label>
                        <span><sup>
                            <i class="fas fa-question-circle" data-toggle="popover" data-trigger="hover" title="Numero Identificador de Usuario" data-content="En el caso de empresas debe utilizar el numero de RUT" data-placement="top">
                            </path></i>
                        </sup></span>
                        <div class="input-group" style="width:30%;">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                            <input id="id_UsuarioMain-identificador" type="text" name="UsuarioMain-identificador" maxlength="12" class="form-control" required autofocus />
                        </div>
                        <span class="helptext text-muted">{{ form.UsuarioMain.identificador.help_text }}</span>
                        <span class="helptext">{{form.UsuarioMain.identificador.errors}}</span>                        
                    </div>
                    <div class="form-group"><label for="id_UsuarioMain-password1">Password</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                            <input id="id_UsuarioMain-password1" type="password" name="UsuarioMain-password1" class="form-control" required/>
                        </div>
                        <span class="helptext text-muted">{{form.UsuarioMain.password1.help_text}}</span>
                        <span class="helptext">{{form.UsuarioMain.password1.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_UsuarioMain-password2">Confirme Password</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                            <input id="id_UsuarioMain-password2" type="password" name="UsuarioMain-password2" class="form-control" required/>
                        </div>
                        <span class="helptext text-muted">{{form.UsuarioMain.password2.help_text}}</span>
                        <span class="helptext">{{form.UsuarioMain.password2.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_UsuarioMain-correo">Correo Electronico</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_UsuarioMain-correo" type="email" maxlength="100" name="UsuarioMain-correo" class="form-control" required/>
                        </div>
                        <span class="helptext text-muted">{{form.UsuarioMain.correo.help_text}}</span>
                        <span class="helptext">{{form.UsuarioMain.correo.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_UsuarioMain-tipo_usuario">Tipo de Usuario</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_UsuarioMain-tipo_usuario" type="text" name="UsuarioMain-tipo_usuario" class="form-control" readonly value="Contribuyente"/>
                        </div>
                        <span class="helptext text-muted">{{form.UsuarioMain.tipo_usuario.help_text}}</span>
                        <span class="helptext">{{form.UsuarioMain.tipo_usuario.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_UsuarioMain-direccion">Dirección</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_UsuarioMain-direccion" type="text" maxlength="100" name="UsuarioMain-direccion" class="form-control" />
                        </div>
                        <span class="helptext text-muted">{{form.UsuarioMain.direccion.help_text}}</span>
                        <span class="helptext">{{form.UsuarioMain.direccion.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_UsuarioMain-telefono">Telefono</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_UsuarioMain-telefono" type="text" maxlength="50" name="UsuarioMain-telefono" class="form-control" />
                        </div>
                        <span class="helptext text-muted">{{form.UsuarioMain.telefono.help_text}}</span>
                        <span class="helptext">{{form.UsuarioMain.telefono.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_UsuarioMain-celular">Celular</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_UsuarioMain-celular" type="text" maxlength="50" name="UsuarioMain-celular" class="form-control" required/>
                        </div>
                        <span class="helptext text-muted">{{form.UsuarioMain.celular.help_text}}</span>
                        <span class="helptext">{{form.UsuarioMain.celular.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_Contribuyente-razon_social">Razon Social</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_Contribuyente-razon_social" type="text" name="Contribuyente-razon_social" class="form-control" maxlength="150" required/>
                        </div>
                        <span class="helptext text-muted">{{form.Contribuyente.razon_social.help_text}}</span>
                        <span class="helptext">{{form.Contribuyente.razon_social.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_Contribuyente-nombre_comercial">Nombre Comercial</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_Contribuyente-nombre_comercial" type="text" maxlength="150" required name="Contribuyente-nombre_comercial" class="form-control" />
                        </div>
                        <span class="helptext text-muted">{{form.Contribuyente.nombre_comercial.help_text}}</span>
                        <span class="helptext">{{form.Contribuyente.nombre_comercial.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_Contribuyente-domicilio_fiscal">Domicilio Fiscal</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_Contribuyente-domicilio_fiscal" type="text" maxlength="150" required name="Contribuyente-domicilio_fiscal" class="form-control"/>
                        </div>
                        <span class="helptext text-muted">{{form.Contribuyente.domicilio_fiscal.help_text}}</span>
                        <span class="helptext">{{form.Contribuyente.domicilio_fiscal.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_Contribuyente-domicilio_constituido">Domicilio Constituido</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_Contribuyente-domicilio_constituido" type="text" maxlength="150" required name="Contribuyente-domicilio_constituido" class="form-control"/>
                        </div>
                        <span class="helptext text-muted">{{form.Contribuyente.domicilio_constituido.help_text}}</span>
                        <span class="helptext">{{form.Contribuyente.domicilio_constituido.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_Contribuyente-n_bps">Número BPS</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_Contribuyente-n_bps" type="number" name="Contribuyente-n_bps" class="form-control" required/>
                        </div>
                        <span class="helptext text-muted">{{form.Contribuyente.n_bps.help_text}}</span>
                        <span class="helptext">{{form.Contribuyente.n_bps.errors}}</span>
                    </div>
                    <div class="form-group"><label for="id_Contribuyente-n_mtss">Número MTSS</label>
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                            <input id="id_Contribuyente-n_mtss" type="number" name="Contribuyente-n_mtss" class="form-control" required/>
                        </div>
                        <span class="helptext text-muted">{{form.Contribuyente.n_mtss.help_text}}</span>
                        <span class="helptext">{{form.Contribuyente.n_mtss.errors}}</span>
                    </div>
                    <div class="form-group form-inline justify-content-between">
                      <div>
                          <input id="GuardarContribuyente" type="submit" value="Guardar Contribuyente" class="btn btn-primary" update="" form="Form_Html_RegistroContribuyente" formmethod="POST" formaction='{% url "Usuarios:Registro_Contribuyente" %}'/>
                      </div>
                    </div>          
                </form>
            </div>    
          </div>
          {% endblock jumbotron_content %}
        {% endblock jumbotron %}
      {% endblock page_content_4 %}
      {% block jscript %}
        <script>
        $(document).ready(function () {
            $('[data-toggle="popover"]').popover();
        });
        </script>
      {% endblock jscript %}  